name: privacy-browser
summary: Privacy Browser
description: |
  Privacy Browser
version: 0.0.1
adopt-info: privacy-browser
grade: stable
confinement: strict
base: core24
contact: https://github.com/kenvandine/privacy-browser/issues
issues: https://github.com/kenvandine/privacy-browser/issues
website: https://github.com/kenvandine/privacy-browser
license: GPL-3.0+
icon: icon512.png

platforms:
  amd64:
  arm64:
compression: lzo

parts:
  privacy-browser:
    plugin: nil
    source: .
    build-packages:
      - npm
      - git
    override-pull: |
      craftctl default
      VERSION=$(craftctl get version)
      if [ -z $VERSION ]; then
        VERSION=$(git describe --tags --abbrev=10)
        craftctl set version=$VERSION
      fi
      sed -i.bak -e "s|@@VERSION@@|$VERSION|g" $CRAFT_PART_SRC/package.json
    override-build: |
      npm install
      npm run build
      mkdir -p $SNAPCRAFT_PART_INSTALL/unpacked
      cp $SNAPCRAFT_PROJECT_DIR/com.github.kenvandine.privacy-browser.desktop $SNAPCRAFT_PART_INSTALL/unpacked/
      cp $SNAPCRAFT_PROJECT_DIR/icon.png $SNAPCRAFT_PART_INSTALL/
      mv dist/linux*-unpacked/* $SNAPCRAFT_PART_INSTALL/unpacked 
    prime:
      - unpacked
      - icon.png
      - -*/chrome-sandbox
      - -*/resources/app.asar.unpacked/node_modules/sharp/vendor/lib
      - -*/resources/app.asar.unpacked/node_modules/sharp/vendor/include

  cleanup:
    after: [ privacy-browser ]
    plugin: nil
    build-snaps: [ gnome-46-2404 ]
    override-prime: |
        set -eux
        cd /snap/gnome-46-2404/current
        find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;

plugs:
  shmem:
    interface: shared-memory
    private: true

apps:
  privacy-browser:
    extensions: [gnome]
    desktop: unpacked/com.github.kenvandine.privacy-browser.desktop
    command: unpacked/privacy-browser --use-tray-icon --no-sandbox --disable-seccomp-filter-sandbox
    plugs:
      - audio-playback
      - audio-record
      - home
      - network
      - shmem
      - unity7
    environment:
      GTK_USE_PORTAL: "1"
      TMPDIR: $XDG_RUNTIME_DIR
      HOME: $SNAP_REAL_HOME
